version: 2.1
tagged_build_filters: &tagged_build_filters
  branches:
    ignore: /.*/
  tags:
    only: /v[0-9]+\.[0-9]+\.[0-9]+/
test_build_filters: &test_build_filters
  branches:
    only: /.*/
  tags:
    ignore: /v[0-9]+\.[0-9]+\.[0-9]+/
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: golint logdna/
  imagetest:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: make build
  build:
    machine:
      docker_layer_caching: true
      # This image contains a more recent version of docker to support `docker manifest`
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Check Tagged Push
          command: |
            PKG_VERSION=$(grep BUILD_VERSION Dockerfile | cut -d'=' -f2)
            if [[ "${CIRCLE_TAG}" != "v${PKG_VERSION}" ]]; then
              echo "There is mismatch:"
              echo "  TAG_VERSION: ${CIRCLE_TAG}"
              echo "  PKG_VERSION: v${PKG_VERSION}"
              exit 1
            fi
      - run: make build
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: .
      - run: go get -u github.com/tcnksm/ghr
      - run:
          name: Create a Release
          command: |
            ghr \
              -n "LogDNA LogSpout ${CIRCLE_TAG}" \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -draft ${CIRCLE_TAG} ./image.tar
  approve:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish:
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202101-01
    steps:
      - attach_workspace:
          at: .
      - run: make publish
workflows:
  update:
    jobs:
      - test:
          filters: *tagged_build_filters
      - build:
          requires:
            - test
          filters: *tagged_build_filters
      - release:
          requires:
            - build
          filters: *tagged_build_filters
      - approve:
          type: approval
          requires:
            - release
          filters: *tagged_build_filters
      - publish:
          requires:
            - approve
          filters: *tagged_build_filters
  test:
    jobs:
      - test:
          filters: *test_build_filters
      - imagetest:
          requires:
            - test
          filters: *test_build_filters
